outpaint:
  output_dir: results
  model_config:
    temporal_path: models/temporal_blocks/mm_sd_v15_v2.ckpt
    control_path: models/inpaint_blocks
    control_scale: 1
    sd_path: models/sd_blocks




  noise_scheduler_kwargs:
    beta_start: 0.00085
    beta_end: 0.012
    beta_schedule: "linear"
    steps_offset: 0 
    clip_sample: false


  training_config:

    learning_rate: 5e-5
    train_batch_size: 1
    max_train_steps: 800
    checkpointing_steps: 99999
    validation_steps: 200
    trainable_modules:
      - "lora"
    seed: 42
    mixed_precision: fp16
    use_8bit_adam: False
    gradient_checkpointing: False
    enable_xformers_memory_efficient_attention: True

    scale_lr: False
    lr_scheduler: "constant"
    lr_warmup_steps: 0
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_weight_decay: 1e-2
    adam_epsilon: 1e-08
    max_grad_norm: 1.0
    gradient_accumulation_steps: 1



